log4j.debug=true   
log4j.rootLogger=DEBUG,D,E

# mybatis sql debug  
#log4j.logger.com.mybatis=DEBUG  
#log4j.logger.com.mybatis.common.jdbc.SimpleDataSource=DEBUG  
#log4j.logger.com.mybatis.common.jdbc.ScriptRunner=DEBUG  
#log4j.logger.com.mybatis.sqlmap.engine.impl.SqlMapClientDelegate=DEBUG  
log4j.logger.java.sql.Connection=DEBUG  
log4j.logger.java.sql.Statement=DEBUG  
log4j.logger.java.sql.PreparedStatement=DEBUG

#log4j.appender.E = org.apache.log4j.ConsoleAppender
#log4j.appender.E.Threshold = DEBUG
#log4j.appender.E.layout = org.apache.log4j.PatternLayout
#log4j.appender.E.layout.ConversionPattern = %-d{yyyy-MM-dd HH:mm:ss}  [ %F:%L ] - [ %p ]  %m%n

log4j.appender.D = org.apache.log4j.ConsoleAppender
log4j.appender.D.Threshold = ERROR
log4j.appender.D.layout = org.apache.log4j.PatternLayout
log4j.appender.D.layout.ConversionPattern = %-d{yyyy-MM-dd HH:mm:ss}  [ %F:%L ] - [ %p ]  %m%n